FROM python:3.10-alpine

RUN python -m venv /venv

WORKDIR /venv

RUN /venv/bin/pip install "python-lsp-server[all]" pyls-flake8 pylsp-mypy pyls-isort python-lsp-black

ENV PATH="/venv/bin:$PATH"

CMD [ "/venv/bin/pylsp" ]
